# This file was generated by GoReleaser. DO NOT EDIT.
cask "xpctl" do
  name "xpctl"
  desc "Interactive TUI for visualizing Crossplane composition pipelines"
  homepage "https://github.com/devriles/xpctl"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xpctl"

  on_macos do
    on_intel do
      url "https://github.com/devriles/xpctl/releases/download/v#{version}/xpctl_#{version}_darwin_amd64.tar.gz"
      sha256 "1d41332f5d8152945967a8c2bd4f51abdd6c49a41823d5475ef3ee0e61cec853"
    end
    on_arm do
      url "https://github.com/devriles/xpctl/releases/download/v#{version}/xpctl_#{version}_darwin_arm64.tar.gz"
      sha256 "6d67972be96d1132c5f7486aed44dae418eceb1a3b552875d2fda531b2a43e33"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devriles/xpctl/releases/download/v#{version}/xpctl_#{version}_linux_amd64.tar.gz"
      sha256 "10ac3089bb4f238fae3988dee3edfba427a89ac8f5ab62b3907b166f4634d695"
    end
    on_arm do
      url "https://github.com/devriles/xpctl/releases/download/v#{version}/xpctl_#{version}_linux_arm64.tar.gz"
      sha256 "e4ee98a99cb4cd4372a05db460ae1fa5b8f161b8b972b968fb3d368ae135ba25"
    end
  end

  # No zap stanza required
end
